# Generated by Django 5.1.6 on 2025-03-17 22:51

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField(default=core.models.tomorrow)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('request_type', models.CharField(choices=[('regular', 'Regular'), ('urgent', 'Urgent')], default='regular', max_length=10)),
                ('jmd_5000', models.IntegerField(default=0)),
                ('jmd_2000', models.IntegerField(default=0)),
                ('jmd_1000', models.IntegerField(default=0)),
                ('jmd_500', models.IntegerField(default=0)),
                ('jmd_100', models.IntegerField(default=0)),
                ('jmd_50', models.IntegerField(default=0)),
                ('usd_100', models.IntegerField(default=0)),
                ('usd_50', models.IntegerField(default=0)),
                ('usd_20', models.IntegerField(default=0)),
                ('usd_10', models.IntegerField(default=0)),
                ('usd_1', models.IntegerField(default=0)),
                ('total_jmd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='EODReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_date', models.DateField(default=core.models.yesterday)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('funds_from_bxp_webex', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash_sent_to_courier', models.BooleanField(default=False)),
                ('courier_usd_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('courier_usd_receipt', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('courier_jmd_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('courier_jmd_receipt', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('all_tellers_balanced', models.BooleanField(default=True)),
                ('total_variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('confirmation', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_reports', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eod_reports', to='core.location')),
            ],
            options={
                'ordering': ['-processing_date'],
                'unique_together': {('agent', 'location', 'processing_date')},
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('denomination', 'Denomination'), ('overage', 'Overage'), ('shortage', 'Shortage')], default='denomination', max_length=20)),
                ('description', models.CharField(default='', max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('currency', models.CharField(choices=[('JMD', 'Jamaican Dollar'), ('USD', 'US Dollar')], default='JMD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eod_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.eodreport')),
            ],
        ),
        migrations.CreateModel(
            name='CashDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.models.today)),
                ('jmd_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cash_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='core.cashrequest')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
            },
        ),
        migrations.CreateModel(
            name='LocationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_limit', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=15)),
                ('eod_vault_limit', models.DecimalField(decimal_places=2, default=3000000.0, max_digits=15)),
                ('working_day_limit', models.DecimalField(decimal_places=2, default=2000000.0, max_digits=15)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='TellerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_name', models.CharField(default='', max_length=255)),
                ('jmd_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('usd_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eod_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teller_balances', to='core.eodreport')),
            ],
        ),
        migrations.CreateModel(
            name='TellerVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_number', models.CharField(default='', max_length=2)),
                ('variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eod_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teller_variances', to='core.eodreport')),
            ],
        ),
        migrations.CreateModel(
            name='DenominationBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('JMD', 'Jamaican Dollar'), ('USD', 'US Dollar')], default='JMD', max_length=3)),
                ('denomination_5000_count', models.IntegerField(default=0)),
                ('denomination_1000_count', models.IntegerField(default=0)),
                ('denomination_500_count', models.IntegerField(default=0)),
                ('coins_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('denomination_100_count', models.IntegerField(default=0)),
                ('denomination_50_count', models.IntegerField(default=0)),
                ('denomination_20_count', models.IntegerField(default=0)),
                ('denomination_10_count', models.IntegerField(default=0)),
                ('small_bills_coins_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eod_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denomination_breakdowns', to='core.eodreport')),
            ],
            options={
                'unique_together': {('eod_report', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='DailyAgentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=core.models.today)),
                ('previous_day_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash_delivered_today', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payout_at_3pm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash_position_at_3pm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('projected_ending_position', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('projected_next_day_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('variance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('exceeds_insurance_limit', models.BooleanField(default=False)),
                ('exceeds_eod_limit', models.BooleanField(default=False)),
                ('exceeds_working_day_limit', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
            ],
            options={
                'unique_together': {('location', 'date')},
            },
        ),
    ]
