# Generated by Django 5.1.6 on 2025-04-10 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_window_enabled', models.BooleanField(default=True, help_text='Enable/disable the 3 PM cutoff window')),
                ('cutoff_hour', models.IntegerField(default=15, help_text='Hour of the day for cutoff (24-hour format)')),
                ('cutoff_minute', models.IntegerField(default=0, help_text='Minute of the hour for cutoff')),
                ('business_hours_start', models.IntegerField(default=8, help_text='Start hour of business hours (24-hour format)')),
                ('business_hours_start_minute', models.IntegerField(default=0, help_text='Start minute of business hours')),
                ('emergency_access_duration', models.IntegerField(default=30, help_text='Duration of emergency access in minutes')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
