# Generated by Django 5.1.6 on 2025-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsettings_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='eft_system_name',
            field=models.CharField(blank=True, default='', help_text='Name of the location in the EFT system', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='insurance_limit_name',
            field=models.CharField(blank=True, default='', help_text='Name used for Insurance Limit purposes', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='remote_services_name',
            field=models.CharField(blank=True, default='', help_text='Name of the location in Remote Services', max_length=255),
        ),
    ]
