# Generated by Django 5.1.6 on 2025-05-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location_eft_system_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('balance_bf', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance Brought Forward', max_digits=15)),
                ('inbound', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('intra_sent', models.DecimalField(decimal_places=2, default=0.0, help_text='Intra-Sent', max_digits=15)),
                ('outbound', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('received_from_gk', models.DecimalField(decimal_places=2, default=0.0, help_text='Received From GK', max_digits=15)),
                ('adjusted', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bx', models.DecimalField(decimal_places=2, default=0.0, help_text='BX', max_digits=15)),
                ('sc', models.DecimalField(decimal_places=2, default=0.0, help_text='SC', max_digits=15)),
                ('fx', models.DecimalField(decimal_places=2, default=0.0, help_text='FX', max_digits=15)),
                ('due_to_gk', models.DecimalField(decimal_places=2, default=0.0, help_text='Due To GK', max_digits=15)),
                ('due_from_gk', models.DecimalField(decimal_places=2, default=0.0, help_text='Due From GK', max_digits=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eft_data', to='core.location')),
            ],
            options={
                'verbose_name': 'EFT Data',
                'verbose_name_plural': 'EFT Data Entries',
                'ordering': ['-statement_date', '-uploaded_at'],
                'unique_together': {('location', 'statement_date')},
            },
        ),
    ]
