# Generated by Django 5.1.6 on 2025-05-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_eftdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteServicesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(help_text='Statement date for the uploaded sheet')),
                ('parish_name', models.CharField(blank=True, max_length=255)),
                ('parish_id', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('pay_principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('send_principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pay_count', models.IntegerField(default=0)),
                ('send_count', models.IntegerField(default=0)),
                ('total_num_trans', models.IntegerField(default=0)),
                ('total_payout_for_location_in_upload', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of Pay Principal for this location in this specific upload/statement date.', max_digits=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_services_data', to='core.location')),
            ],
            options={
                'verbose_name': 'Remote Services Data',
                'verbose_name_plural': 'Remote Services Data Entries',
                'ordering': ['-statement_date', 'location__name', '-uploaded_at'],
            },
        ),
    ]
